name: Maven Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  invoke-release:
    uses: emergentdotorg/github-actions/.github/workflows/reusable-maven-release.yml@main
    secrets: inherit
    with:
      java-version: '8'

  process-results:
    runs-on: ubuntu-latest
    needs: invoke-release
    steps:
      - run: echo version=${{ needs.invoke-release.outputs.version }}
