name: Maven Release

on:
  workflow_dispatch:
    inputs:
      next-release-version:
        description: 'Next Release Version'
      next-snapshot-version:
        description: 'Next Snapshot Version'
      dry-run:
        description: 'Dry-run'
        type: boolean
        required: false
        default: false

jobs:
  call-workflow:
    uses: emergentdotorg/github-actions/.github/workflows/reusable-maven-release.yml@1
    with:
      java-version: '8'
      next-release-version: ${{ inputs.next-release-version }}
      next-snapshot-version: ${{ inputs.next-snapshot-version }}
      dry-run: ${{ inputs.dry-run }}
    secrets: inherit
